feat(youtube-scrape): Add yt scrape option
Hazmi35/jukebox pull request #300
Opened 2020-12-20 12:47 UTC by KurokuTetsuya

2020-12-20 12:48 UTC, KurokuTetsuya commented
This will solve #224

2020-12-20 12:49 UTC, KurokuTetsuya commented
![image](https://user-images.githubusercontent.com/45705890/102713656-66463100-42fc-11eb-87c1-0990bf0459f5.png)
Still have some problem with playlist extraction.

2020-12-20 15:40 UTC, Hazmi35 requested changes

2020-12-20 15:40 UTC, Hazmi35 commented on .env.example
> +CONFIG_YOUTUBE_SCRAPE=yes # Whether to scrape youtube instead using api. You may not fill the API config if you use this.
```suggestion
CONFIG_YOUTUBE_SCRAPE=yes # Whether to scrape youtube instead using API.
```
This description should be moved to YT_API_KEY's comment

2020-12-20 15:40 UTC, Hazmi35 commented on .env.schema
> +CONFIG_YOUTUBE_SCRAPE=
Please add this environment variable in app.json too

2020-12-20 15:40 UTC, Hazmi35 commented on src/commands/PlayCommand.ts
> +        if (this.client.config.youtubeScrape) {
This should be moved to the Jukebox client, but by this, you need to make the interface the same as YoutubeAPI

2020-12-20 15:40 UTC, Hazmi35 commented on src/config.ts
> +if (youtubeScrape && process.env.YT_API_KEY) console.warn("[WARN] You may not fill YT_API_KEY because you enable youtube scrapping which doesn't require API key.");
Is this necessary? I think not

2020-12-20 15:40 UTC, Hazmi35 commented on src/utils/YoutubeScrape/index.ts
> +    }
Can you use ISO8601 Duration instead?

2020-12-20 15:40 UTC, Hazmi35 commented on src/utils/YoutubeScrape/structures/Video.ts
> +        // You can do manual eliminate by using http request and check the response status
Hmm, I'll try to find a solution to this

2020-12-20 16:13 UTC, Hazmi35 requested changes

2020-12-20 16:13 UTC, Hazmi35 commented on .env.example
> +YT_API_KEY=IAzSjcSjaIEWakos-_AKfaKejiwdjiASJIAsDs # Your Youtube API key. You may not fill the API config if you use CONFIG_YOUTUBE_SCRAPE.
```suggestion
YT_API_KEY=IAzSjcSjaIEWakos-_AKfaKejiwdjiASJIAsDs # Your Youtube API key. You don't need to fill this if you use CONFIG_YOUTUBE_SCRAPE.
```

2020-12-20 16:13 UTC, Hazmi35 commented on app.json
> +            "description": "Youtube API Key for querying the Youtube API for video data. You may not fill the API config if you use CONFIG_YOUTUBE_SCRAPE."
```suggestion
            "description": "Your Youtube API key. You don't need to fill this if you use CONFIG_YOUTUBE_SCRAPE."
```

2020-12-20 16:13 UTC, Hazmi35 commented on app.json
> +            "description": "Whether to scrape youtube instead using API."
```suggestion
            "description": "Whether to scrape youtube instead using API.",
            "required": false
```

2020-12-20 16:13 UTC, Hazmi35 commented on src/commands/PlayCommand.ts
> +        if (this.client.config.youtubeScrape) {
Why is this resolved?

2020-12-20 16:13 UTC, Hazmi35 commented on src/structures/Jukebox.ts
> +    public readonly youtubeScrapper = new YoutubeScrape(this);
I think you should make merge this to Jukebox#youtube

2021-01-27 09:42 UTC, mzrtamp approved these changes

2021-02-03 16:43 UTC, mzrtamp commented
🙁

2021-02-06 03:58 UTC, mzrtamp commented
[`ZenForks:feat/youtube-scrape`](https://github.com/ZenForks/jukebox/pull/4) why could this thing be skipped?

2021-02-06 04:59 UTC, closed without merging