refactor(messaging): change the bot's messaging to make it comfortable to read
Hazmi35/jukebox pull request #337
Opened 2021-01-24 14:59 UTC by mzrtamp

Sorry for a useless commit, but I found an unnecessary thing on this PR

2021-01-26 02:42 UTC, Hazmi35 requested changes
Great PR, thank you!

2021-01-26 02:42 UTC, Hazmi35 commented on src/commands/HelpCommand.ts
> +                    .setTitle(`Information for ${command.meta.name} command`)
```suggestion
                    .setTitle(`Information for the ${command.meta.name} command`)
```
Add `the` before the command name

2021-01-26 02:42 UTC, Hazmi35 commented on src/commands/NowPlayingCommand.ts
> +    description: "Send an info about current music player",
```suggestion
    description: "Send info about the current music player",
```

2021-01-26 02:42 UTC, Hazmi35 commented on src/commands/PauseCommand.ts
> +            return message.channel.send(createEmbed("info", "⏸ The music player has been paused!"));
```suggestion
            return message.channel.send(createEmbed("info", "⏸ The music player paused"));
```
Eh, this was better imo

2021-01-26 02:42 UTC, Hazmi35 commented on src/commands/PauseCommand.ts
> +        message.channel.send(createEmbed("warn", "❗ Music player is already paused!"))
```suggestion
        message.channel.send(createEmbed("warn", "❗ The music player is already paused!"))
```

2021-01-26 02:42 UTC, Hazmi35 commented on src/commands/PingCommand.ts
> +        message.channel.send("🏓 Pinging...").then((msg: IMessage | any) => {
```suggestion
        message.channel.send("🏓 Pong!").then((msg: IMessage | any) => {
```
This message should be pong because the user goes with "jukebox ping" then the bot should respond with pong, not ping

2021-01-26 02:42 UTC, Hazmi35 commented on src/commands/PlayCommand.ts
> +                createEmbed("warn", `The music player is already playing to: **${message.guild?.queue.voiceChannel?.name}** voice channel`)
```suggestion
                createEmbed("warn", `The music player is already playing to **${message.guild?.queue.voiceChannel?.name}** voice channel`)
```
Should we remove the colon?

2021-01-26 02:42 UTC, Hazmi35 commented on src/commands/PlayCommand.ts
> +                        .setFooter("Please select one of the results ranging 1-12"));
```suggestion
                        .setFooter("Please select one of the results ranging from 1-12"));
```

2021-01-26 02:42 UTC, Hazmi35 commented on src/commands/PlayCommand.ts
> +                        return message.channel.send(createEmbed("info", "Song selection has been canceled."));
```suggestion
                        return message.channel.send(createEmbed("info", "Song selection canceled."));
```
Isn't this better?

2021-01-26 02:42 UTC, Hazmi35 commented on src/commands/PlayCommand.ts
> +                message.channel.send(createEmbed("error", `I can't join to the voice channel!\nError: \`${error.message}\``))
```suggestion
                message.channel.send(createEmbed("error", `Error: Could not join the voice channel!\nReason: \`${error.message}\``))
```
This is fine

2021-01-26 02:42 UTC, Hazmi35 commented on src/commands/ResumeCommand.ts
> +            message.channel.send(createEmbed("info", "▶ Resumed the music player!")).catch(e => this.client.logger.error("RESUME_CMD_ERR:", e));
```suggestion
            message.channel.send(createEmbed("info", "▶ The music player resumed")).catch(e => this.client.logger.error("RESUME_CMD_ERR:", e));
```

2021-01-26 02:42 UTC, Hazmi35 commented on src/commands/QueueCommand.ts
> +            .setTitle("Song Queue")
```suggestion
            .setTitle("Music Queue")
```
I better be renaming all the variables from song to music too, lol

2021-01-26 02:42 UTC, Hazmi35 commented on src/commands/StopCommand.ts
> +        message.channel.send(createEmbed("info", "⏹ The queue has been stopped."))
```suggestion
        message.channel.send(createEmbed("info", "⏹ Queue stopped."))
```
Queue stopped is good, but delete the 2 dot

2021-01-26 02:42 UTC, Hazmi35 commented on src/listeners/MessageEvent.ts
> +                createEmbed("info", `Hi, I am a simple music bot, see my commands with \`${this.client.config.prefix}help\``)
```suggestion
                createEmbed("info", `Hi, I'm a simple music bot, see my commands with \`${this.client.config.prefix}help\``)
```
Don't need the change here

2021-01-26 02:42 UTC, Hazmi35 commented on src/utils/decorators/MusicHelper.ts
> +                createEmbed("warn", "You need to be in a same voice channel as mine")
```suggestion
                createEmbed("warn", "You need to be in the same voice channel as mine")
```

"in the same" is correct, but "in a same" is not

2021-01-26 02:42 UTC, Hazmi35 commented on src/utils/decorators/MusicHelper.ts
> +            return message.channel.send(createEmbed("error", "I'm sorry, but I can't connect to your voice channel, make sure I have a proper permissions!"));
```suggestion
            return message.channel.send(createEmbed("error", "I'm sorry, but I can't connect to your voice channel, make sure I have the proper permissions!"));
```
`the` is correct

2021-01-26 02:42 UTC, Hazmi35 commented on src/utils/decorators/MusicHelper.ts
> +            return message.channel.send(createEmbed("error", "I'm sorry, but I can't speak in this voice channel. make sure I have a proper permissions!"));
```suggestion
            return message.channel.send(createEmbed("error", "I'm sorry, but I can't speak in this voice channel. make sure I have the proper permissions!"));
```

2021-01-27 09:32 UTC, mzrtamp commented on src/commands/PingCommand.ts
> +        message.channel.send("🏓 Pinging...").then((msg: IMessage | any) => {
Hmmm, ok

2021-01-27 09:35 UTC, mzrtamp commented on src/commands/PlayCommand.ts
> +                        return message.channel.send(createEmbed("info", "Song selection has been canceled."));
Ok then

2021-01-27 09:35 UTC, mzrtamp commented on src/listeners/MessageEvent.ts
> +                createEmbed("info", `Hi, I am a simple music bot, see my commands with \`${this.client.config.prefix}help\``)
Hmm :/

2021-01-27 09:36 UTC, mzrtamp commented on src/utils/decorators/MusicHelper.ts
> +                createEmbed("warn", "You need to be in a same voice channel as mine")
Sorry

2021-01-27 09:37 UTC, mzrtamp commented on src/commands/PlayCommand.ts
> +                message.channel.send(createEmbed("error", `I can't join to the voice channel!\nError: \`${error.message}\``))
Uhh huh...

2021-01-27 09:38 UTC, mzrtamp commented on src/commands/QueueCommand.ts
> +            .setTitle("Song Queue")
Oh my

2021-01-27 09:41 UTC, mzrtamp commented
Oops, sorry for too many commits, because I did this manually via [**GitHub website**](https://github.com) directly

2021-01-27 10:26 UTC, Hazmi35 requested changes
We miss one here

2021-01-27 10:26 UTC, Hazmi35 commented on src/commands/VolumeCommand.ts
> +                createEmbed("warn", `❗ I can't set the volume above ${this.client.config.maxVolume}`)
```suggestion
                createEmbed("warn", `❗ I can't set the volume above \`${this.client.config.maxVolume}\``)
```

2021-01-27 10:27 UTC, mzrtamp commented on src/commands/VolumeCommand.ts
> +                createEmbed("warn", `❗ I can't set the volume above ${this.client.config.maxVolume}`)
lmao

2021-01-27 10:28 UTC, mzrtamp commented
Right

2021-01-27 10:31 UTC, Hazmi35 approved these changes
Great work. Thanks for your contribution!

2021-01-27 10:33 UTC, merged